repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0 # Use a recent tag
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-added-large-files
    - id: debug-statements

# Ruff hooks (linter and formatter)
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version should match the one in pyproject.toml (or be compatible)
  rev: v0.4.10 # Use a recent tag matching your Ruff version if possible
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format 